# Generated by Django 4.2.6 on 2023-10-08 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=255)),
                ('type', models.CharField(choices=[('VI', 'Vietnamese'), ('EN', 'English'), ('OT', 'Other')], default='EN', max_length=2)),
                ('slug', models.CharField(default='', max_length=255, unique=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('title', models.CharField(default='', max_length=255)),
                ('status', models.CharField(choices=[('ON', 'on'), ('OFF', 'off')], default='OFF', max_length=3)),
                ('created_time', models.CharField(default='', max_length=255)),
                ('full_width', models.BooleanField(default=False)),
                ('experience', models.TextField(default='')),
                ('work_status', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CvItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cv')),
            ],
        ),
    ]
